sudo: required
dist: trusty
language: node_js
node_js:
- node
- '7'
env:
  global:
  - secure: A99Lx1l6uQ3ctJNFRO65V1URIrEjZMgrY0uWHodVVD6a8tUctm6lng6b4MiTU2qXOMWewVHnFXOBxcc/llB+SkxmV+lkcfFD69hoMbGJApdJD5hhouLB1pkQuGeFNEGbac+QHi6gY16nbdwZWRWZkp4FEkFbV3c/3GzVd21DTMGkqz5GVlIC1nGMOiKhq66zIDUOEF64tg6C/OHWFV1ZxTAWUHHtd01NbT0IywI6NENbZAM36lICOHvUGLiCUf/nmcgB/g5D4zSVYsxnDnLdKaaEGfWkdS4BiFaA8O81UqX46N3mh8E1m2ZARUT3k1yWaLVpWhDiBw+OQ4ZHAWWU6AygQsjMgd57Yxk8Pw7ndxd12imseq9In3akBqarljcCyc8UdPH3zrqn0X3ysJXEe29o/5pz0j3pZRa+2f9eitVr8MK7TySJmqNnw+Msrr/R9ENLpHkxtCKdy5GgPfBITSu3TGib4fZOHJ0H6gVYqWldfUxj7Ox7cDCMTVbWs1azW+XYIiAQiXDvRU+Sbj5Q+k2cDLH76PuDE3KYEdUlk87tcXk/iopKqIZ9vvDCAPQOq3IbMLqhMMWJZFrAEjbXOrbBLDg6XUZuY0BOMW/vXIM8Wtkl2esOwHx/pML6+dVihb5PZ1wCoBzs/3deECKTSnmUf80OCowdk36+4NwIk8Y=
  - secure: PQTJ6TGC0YAC81C4PGxSf7Bz3SwIYV6kBHFFdqlPebL7Srjr2yJnRjX9LuJo+Iog/7VLxFLxIP9Fzrd18y6XneEhRaxj4fCHcf0eYJLF8Fg3X/Bvd7dOc2Zc5uJSAgxf30M7LwiBdBDvRs4OFyaLFKYIvMBov4h5FDPKE9RR5YQ9CbV6AFnbZMtFwBeomxk2peP29myjPCNym8oL6QHiEgUePSYIF55rimzNfcS/xcHU7SCRO+WjADgTqtSr73zPPBIlGHPmFNU+ymVMjAjytkPQ4cPQRAease5KBRHkuiFW4K7hg5iGQSEnCjBekBh5reQ+J86JtgoA5oQh2/fyZq7XG2+pWRt/eWUZso76BqqVCdP4Ir8gSvRfkkPTBAD/2io57hkPdJhom68DfrwmyxgSHJqzYJV6e6AwBR42LoAUoOMM0t+MY4Uxuqb2JfkP7Bcw46RUTxd34Yw+O/0HTkL+q7eYqHd29zRU6cthVjQH9MrHCFjnN7M5/XaeTUYCx2x2gkz+MSdq91qulNRI8APZyNry3sX+m6uOTyRBd5C/oJrSpO+ZcW5mYx6CXJXYDwlx1PNnN9Oqn/fVzLvZUkzR1JVwfwcOSnZjSMQRd498v07o5bCKZB77G1hOPGJiJVrVU8D2evwSrIRtIlVpTiL14HJr+yZ8MSX5GEdXuRA=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_fb7ffa7efc8b_key -iv $encrypted_fb7ffa7efc8b_iv
  -in docker-creds.tar.enc -out docker-creds.tar -d
- tar xvf docker-creds.tar
- docker login -u $DOCKER_USER -p $DOCKER_PASS
stages:
- name: build
- name: deploy
jobs:
  include:
  - stage: build
    script:
    - docker build --pull --rm -t threethink/shit-city-image-upload-service:${TRAVIS_COMMIT} .
    - docker push threethink/shit-city-image-upload-service:${TRAVIS_COMMIT}
    if: branch = master
  - stage: deploy
    env:
    - secure: SC/+PSBcM+SB9sAeznzCMW52MXc2b440HwnHGWBYtwpRuAgQa4Tm+ZCE95QLGRzqS6mLG2NH7BvvMNcP41SjtetDmmKMWdVS+1X/iONRrjK3oJrwvMz6PG7cz02CuRrOd1Y0IV16cXQ/GgQ9i/UCELONi3w4GfrBirEGb08pW8FplVqFE/5SeP4KxxKBqGrnBHWC7woThdGHUQvcSVukZC04hfpnYyvr8bKXCVXGba7LuLciPDo1mDkJfXowD3ldnutvPTLLTWB3KLTuXcfvNIZgP6U8pJUxLK9tECXRbBaM9IK/VYB7swMPeoU0jRXgmKvVhXFD6yAnwxr4jiq957pDLY3a8m+rgV74cZJqcYaf458uuFac7TWAt9e43uTumjZxiKp2BPhEu+Jp7MenV9ia+5TxblPaMUijhqF02KJ2LXj73vQCd75F4h4wy+czblpKTRCWvYYzN3OQX7FLBIXXO3L8Zl/5DBdj1l/Hcw7B7LN3vRnExENTZI8OQYi3cS3t9qtHaVJYeTS7+8v2pLYNZD8k71nRcisNtM3gKvJ0hQp9z0gahmKFnn+V+j1gXFskbb1ODO6Enj5Zxx2ASZum7AXxX2JEnQUpcEv5tB8PYjMiB1TtCKVXvsgrIR29p7tZyu4wH0885UVVoByFqssR9FiMZhKZ17D72N/NvpE=
    - DOCKER_CERT_PATH="./docker-creds"
    - DOCKER_TLS_VERIFY="True"
    script: docker-compose up -d
    if: branch = master
