version: '2.3'
services:
  shit-city-image-upload:
    image: threethink/shit-city-image-upload:${TRAVIS_COMMIT}
    scale: 2
    labels:
      - "traefik.enable=true"
      - "traefik.backend=shit-city-image-upload" #backend name
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:image-upload.andimenge.de"
      - "traefik.frontend.auth.basic=app:$$apr1$$G9D2C9xd$$U943CoG6f94md2hl86zae/" #escape single $ with another $
    cpu_count: 1
    mem_reservation: 100m
    mem_limit: 1500000000
    restart: on-failure
    volumes:
      - "/data/images/uploads:/uploads"    
    networks:
      - production
networks:
  production:
    external: true #let it be accessable from everywhere for testing purposes